version: '3.8'

services:
  python-backend:
    build:
      context: .  
    ports:
      - "5000:5000"  
    volumes:
      - .:/app 
    environment:
      - FLASK_APP=main.py  
    command: python main.py  
    restart: always  
    working_dir: /app
